export enum Providers {
    CONFIABILIDADE_ADAPTER = "CONFIABILIDADE_ADAPTER",
    CONFIABILIDADE_SERVICE = "CONFIABILIDADE_SERVICE",
    CONTRATO_ADAPTER = "CONTRATO_ADAPTER",
    CONTRATO_SERVICE = "CONTRATO_SERVICE",
    DEMANDA_ADAPTER = "DEMANDA_ADAPTER",
    DEMANDA_SERVICE = "DEMANDA_SERVICE",
    SIMULADOR_ADAPTER = "SIMULADOR_ADAPTER",
    SIMULADOR_SERVICE = "SIMULADOR_SERVICE",
    TARIFA_ADAPTER = "TARIFA_ADAPTER",
    TARIFA_SERVICE = "TARIFA_SERVICE",
}