export enum Providers {
    ContratoAdapter = "ContratoAdapter",
    ContratoService = "ContratoService",
    ContratoQueryGenerator = "ContratoQueryGenerator",
    ParamAdapter = "ParamAdapter",
    ParamService = "ParamService",
    PenalidadeQueryBuilder = "PenalidadeQueryBuilder",
    PenalidadeAdapter = "PenalidadeAdapter",
    PenalidadeService = "PenalidadeService",
    PontoAdapter = "PontoAdapter",
    PontoService = "PontoService",
    SimuladorAdapter = "SimuladorAdapter",
    SimuladorService = "SimuladorService",
    SimuladorQueryBuilder = "SimuladorQueryBuilder",
}