export enum Providers {
    ContratoAdapter = "ContratoAdapter",
    ContratoService = "ContratoService",
    ContratoQueryGenerator = "ContratoQueryGenerator",
    CsvParser = "CsvParser",
    DateUtils = "DateUtils",
    ParamAdapter = "ParamAdapter",
    ParamService = "ParamService",
    PenalidadeQueryBuilder = "PenalidadeQueryBuilder",
    PenalidadeAdapter = "PenalidadeAdapter",
    PenalidadeService = "PenalidadeService",
    PontoAdapter = "PontoAdapter",
    PontoService = "PontoService",
    SharepointContratoAdapter = "SharepointContratoAdapter",
    SharepointContratoService = "SharepointContratoService",
    SharepointDemandaAdapter = "SharepointDemandaAdapter",
    SharepointDemandaService = "SharepointDemandaService",
    SharepointParamAdapter = "SharepointParamAdapter",
    SharepointParamService = "SharepointParamService",
    SimuladorAdapter = "SimuladorAdapter",
    SimuladorService = "SimuladorService",
    SimuladorQueryBuilder = "SimuladorQueryBuilder",
}