insert into edp.ponto (id, nome, empresa, createdAt) VALUES
('CAM', 'Campos', 'ES', now()),
('JNE', 'João Neiva', 'ES', now()),
('LIN', 'Linhares 2', 'ES', now()),
('RNS', 'Rio Novo do Sul', 'ES', now()),
('SMT', 'São Mateus 2', 'ES', now()),
('MAC', 'Mascarenhas', 'ES', now()),
('VER', 'Verona', 'ES', now()),
('VIA', 'Viana', 'ES', now()),
('VIT', 'Vitória', 'ES', now()),
('VPV', 'Vila Paiva 88kV', 'SP', now()),
('AER', 'Aeroporto 138kV', 'SP', now()),
('AAZ', 'Água Azul 138kV', 'SP', now()),
('APA', 'Aparecida 88kV', 'SP', now()),
('BAR', 'Barra do Una 138kV', 'SP', now()),
('BIR', 'Biritiba 138kV', 'SP', now()),
('BOI', 'Boissucanga 138kV', 'SP', now()),
('CRG', 'Caraguatatuba 88kV', 'SP', now()),
('CEB', 'Cebrasp 88kV', 'SP', now()),
('EMB', 'Embraer 88kV', 'SP', now()),
('PTG', 'Petrobrás Gleba D 138kV', 'SP', now()),
('ITA', 'Itapeti 88kV', 'SP', now()),
('JAM', 'Jambeiro 88kV', 'SP', now()),
('JUQ', 'Juquehy', 'SP', now()),
('MAN', 'Manuel Areias 138kV', 'SP', now()),
('MAR', 'Maresias 138kV', 'SP', now()),
('MAS', 'Massaguaçú 138kV', 'SP', now()),
('MRS', 'Mars 88kV', 'SP', now()),
('MMM', 'Mogi 230kV', 'SP', now()),
('MOG', 'Mogi 88kV', 'SP', now()),
('NDE', 'Nordeste 88kV', 'SP', now()),
('NOR', 'Norte 88kV', 'SP', now()),
('OLA', 'Olaria 138kV', 'SP', now()),
('PET', 'Petrom 138kV', 'SP', now()),
('PLM', 'Polimix', 'SP', now()),
('PTN', 'Porto Novo 138kV', 'SP', now()),
('PTR', 'Petrobrás RPO 138kV', 'SP', now()),
('SJC', 'São José dos Campos 88kV', 'SP', now()),
('STC', 'Santa Cabeça 88kV', 'SP', now()),
('SLZ', 'Santa Luzia138kVA', 'SP', now()),
('SEB', 'São Sebastião 13,8kV', 'SP', now()),
('DCT', 'DCTA 88kV', 'SP', now()),
('SIF', 'Sifão 138kV', 'SP', now()),
('SKL', 'Skol 88kV', 'SP', now()),
('TAU', 'Taubaté 138kV', 'SP', now());